name: CMake on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: |
          sudo apt-get update && sudo apt-get install -y mingw-w64
          sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Prepare binaries
      run: |
          ls -lah ${{github.workspace}}/../
          mkdir ${{github.workspace}}/output
          cp ${{github.workspace}}/../binkw32.dll ${{github.workspace}}/output/binkw32.dll
          cp ${{github.workspace}}/README.md  ${{github.workspace}}/output/.

    - uses: actions/upload-artifact@v4
      with:
        path: ${{github.workspace}}/output



